server:
  port: 7001

spring:
  application:
    name: zuul_gateway_service
  redis:
    # Redis数据库索引（默认为0）
    database: 0
    # Redis服务器地址
    host: 127.0.0.1
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password:
    jedis:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 200
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
        # 连接池中的最大空闲连接
        max-idle: 10
        # 连接池中的最小空闲连接
        min-idle: 0
    # 连接超时时间（毫秒）
    #timeout: 0

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: zuul_gateway_7001

zuul:
  routes:
    systemManager.serviceId: provider-systemManagement
    systemManager.path: /systemManager/**
  prefix: /neusoftMall
  ignored-services: "*"
  host:
    connect-timeout-millis: 3000
    socket-timeout-millis: 3000
