server:
  port: 8001

spring:
  application:
    name: provider-systemManagement
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/neusoftMall?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
  redis:
    # Redis数据库索引（默认为0）
    database: 0
    # Redis服务器地址
    # host: 192.168.74.135
    host: 127.0.0.1
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password:
    jedis:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 200
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
        # 连接池中的最大空闲连接
        max-idle: 10
        # 连接池中的最小空闲连接
        min-idle: 0
    # 连接超时时间（毫秒）
    timeout: 0

mybatis:
  mapper-locations: classpath:mybatis/mapper/**/*.xml
  #开启驼峰命名转换
  configuration:
    map-underscore-to-camel-case: true

eureka:
  instance:
    prefer-ip-address: true
    instance-id: provider-systemManagement-8001
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/ #设置与Eureka Server交互的地址

logging:
  level:
    com.neusoft: debug   # 打印sql

rootId: 0 #菜单树的根节点
loginTimeOut: 1200 #60*20 表示20分钟